import { portfolio } from '../data/content.js';

const card = (edit, i) => `<article class="edit-card js-magnetic js-ripple ${edit.featured ? 'edit-card--featured' : ''} ${edit.tall ? 'edit-card--tall' : ''}"><div class="card-kicker"><span>${String(i + 1).padStart(2, '0')}</span><span>${edit.meta}</span></div><h2>${edit.title}</h2><p>${edit.description}</p></article>`;
const skill = (item) => `<div class="skill-meter js-magnetic" style="--p:${item.value}%"><header><span>${item.name}</span><b>${item.value}%</b></header><i></i></div>`;
const contact = (item) => `<a class="contact-card js-magnetic js-ripple" href="${item.href}" ${item.href.startsWith('http') ? 'target="_blank" rel="noopener noreferrer"' : ''}><strong>${item.label}</strong><span>${item.value}</span></a>`;

export function renderViews() {
  const edits = document.querySelector('[data-view="edits"]');
  const skills = document.querySelector('[data-view="skills"]');
  const contactView = document.querySelector('[data-view="contact"]');
  if (edits) edits.innerHTML = `<div class="page-head"><div><p class="eyebrow reveal">Edits / cuts / rhythm</p><h1 id="edits-title" class="page-title reveal">EDITS</h1><p class="page-copy reveal">Cinematic edits, beat sync visuals, transition cuts, music video cuts and social ads built with rhythm and retention.</p></div><div class="page-orbit reveal"><div class="orbit-core"><strong>06</strong><span>edit styles</span></div></div></div><div class="card-grid">${portfolio.edits.map(card).join('')}</div>`;
  if (skills) skills.innerHTML = `<div class="page-head"><div><p class="eyebrow reveal">Skills / workflow / tools</p><h1 id="skills-title" class="page-title reveal">SKILLS</h1><p class="page-copy reveal">A technical lab for rhythm, transitions, grading, sound design and motion polish.</p></div><div class="page-orbit reveal"><div class="orbit-core"><strong>96</strong><span>editing score</span></div></div></div><div class="skill-layout"><div class="skill-panel">${portfolio.skills.map(skill).join('')}</div><div class="stack-panel"><div class="stack-orbit">${portfolio.tools.map(t => `<span class="tool-chip js-magnetic">${t}</span>`).join('')}</div></div></div>`;
  if (contactView) contactView.innerHTML = `<div class="page-head"><div><p class="eyebrow reveal">Booking / collabs</p><h1 id="contact-title" class="page-title reveal">CONTACT</h1><p class="page-copy reveal">For creators, brands and artists who need sharp visuals and edits that hit fast.</p></div><div class="page-orbit reveal"><div class="orbit-core"><strong>24H</strong><span>reply target</span></div></div></div><div class="contact-layout"><div class="booking-panel"><h2>Work with Shahine.</h2><p>Send the brief, references, deadline and platform. The edit direction is built around rhythm, retention and premium finish.</p><div class="contact-list">${portfolio.contact.map(contact).join('')}</div></div><div class="contact-poster js-magnetic"><div class="contact-poster__inner"><p class="eyebrow">Premium edit request</p><h2>Send clips. Get impact.</h2><p>Short-form edits, music visuals and brand assets.</p></div></div></div>`;
}
